vendor: SUTO
model: SUTO_FLOWMETER
slave_id: 1

flow:
  min: 0.0
  max: 100.0
  value: 50.0
  profile:
    type: wave
    period: 20
    amplitude: 30

consumption:
  min: 0
  max: 1000
  value: 100
  profile:
    type: ramp
    step: 5

revconsumption:
  min: 0
  max: 500
  value: 50

direction:
  value: 0
